source "https://github.com/virgilius-santos/VSCommonSwiftLibrary.git"

platform :ios, '12.4'

use_frameworks!

target 'VService' do

  pod "VCore"

  target 'VServiceTests' do
    pod 'Quick'
    pod 'Nimble'
  end
end