source 'https://github.com/virgilius-santos/public-pod-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.4'

use_frameworks!

target 'VCore' do
  pod 'Willow'        , '~> 5.0', :inhibit_warnings => true
end

target 'VCoreTests' do 
  pod 'Quick'       , '~> 2.2', :inhibit_warnings => true
  pod 'Nimble'      , '~> 8.0', :inhibit_warnings => true
end