source 'https://github.com/virgilius-santos/public-pod-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.4'

use_frameworks!

target 'VComponents' do

  target 'VComponentsTests' do
    pod 'Quick'
    pod 'Nimble'
  end
end
